### ISSUE TITLE
偶尔会超时

### ISSUE THREAD

**Issue by yihong0618** [Yikun/hub-mirror-action#100]
作者你好，
感谢你的项目，我用你的 Actions 设置的 crontab 偶尔会超时一次，我是 1 小时 1 跑，超时频率不确定。但基本上每天会发生至少一次。
![image](https://user-images.githubusercontent.com/15976103/114117648-b97ad880-9919-11eb-825d-daf47a6df4c2.png)

![image](https://user-images.githubusercontent.com/15976103/114117548-88020d00-9919-11eb-8505-d7c7f07dc2ae.png)

Actions 地址 https://github.com/yihong0618/blog/actions

**Comment by yi-Xu-0100** [comment]
@yihong0618 似乎是 gitee api 不稳定造成的，不太建议同步设置这么频繁，设置为定时时间长点，然后同时设置push触发，和手动启动比较好。

**Comment by yihong0618** [comment]
@yi-Xu-0100 
谢谢。

**Comment by Yikun** [comment]
@yihong0618 感谢反馈。

是的，这个是因为gitee的api接口不稳定造成的，这个错误是在访问gitee的查询列表时超时导致的。

我们会在调用gitee api的时候，加一个类似[git操作重试](https://github.com/Yikun/hub-mirror-action/blob/132b206a796926508b73fe82e9f3bb0969a3add6/hub-mirror/mirror.py#L24)的重试机制，去解决这个问题。

当然@yi-Xu-0100 提到的减少同步次数也是一个缓解的方法。

**Comment by yihong0618** [comment]
@Yikun 

Cool, 明白了，再次感谢。

**Comment by yi-Xu-0100** [comment]
@Yikun 

最近我的每日同步任务也出现失败现象。https://github.com/yi-Xu-0100/hub-mirror/actions
```
HTTPSConnectionPool(host='gitee.com', port=443): Max retries exceeded with url: /api/v5/users/yiXu0100/repos?page=0&per_page=60 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f56a0191c70>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```
似乎这个请求会对每次的同步都请求一次，而如果进行的是多 repo 的同步，则更容易造成错误。是否应该是任务启动的第一步获取完整列表以备后面使用。

**Comment by Yikun** [comment]
> 是否应该是任务启动的第一步获取完整列表以备后面使用。

是的，目前的实现，是在创建的时候，对于每个仓库都会检查一下目的端是否存在（获取目的仓列表，然后check是否存在）：
https://github.com/Yikun/hub-mirror-action/blob/869c368c30fda92c438de1ccdfe10d60a0631be3/hub-mirror/hub.py#L57

这个地方是可以优化一下，在最开始的时候，获取一个目的端的列表，然后在has_repo check的时候，只用检查这个列表即可。

**Comment by Yikun** [comment]
> 这个地方是可以优化一下，在最开始的时候，获取一个目的端的列表，然后在has_repo check的时候，只用检查这个列表即可。

https://github.com/Yikun/hub-mirror-action/blob/869c368c30fda92c438de1ccdfe10d60a0631be3/hub-mirror/hub.py#L88-L89

这里有LRU cache了，所以不需要优化。（自己写的代码给忘记了- -

关闭
