### ISSUE TITLE
报错解包的值太多，是说的啥意思

### ISSUE THREAD

**Issue by WTxiaomage** [Yikun/hub-mirror-action#126]
![image](https://user-images.githubusercontent.com/20138139/143804036-414b0cea-0d61-4774-a541-947f73ea5d7a.png)
 File "/hub-mirror/hubmirror.py", line 52, in run
    hub = Hub(
  File "/hub-mirror/hub.py", line 14, in __init__
    self.src_type, self.src_account = src.split('/')
ValueError: too many values to unpack (expected 2)

**Comment by yi-Xu-0100** [comment]
@WTxiaomage 仓库或者使用的配置内容，方便给出吗？

**Comment by Yikun** [comment]
https://github.com/WTxiaomage/react-blog/commit/4b75b82b5394117a3187c282a3fb1eb46ad87a86
```
        src: github/git@github.com:WTxiaomage/react-blog.git  # 源端账户名(github)
        dst: gitee/git@gitee.com:WTxiaomage_admin/react-blog.git  # 目的端账户名(gitee)
```
这块有问题：
```
src: github/WTxiaomage
dst: gitee/WTxiaomage_admin
# white_list: react-blog
# static_list: react-blog
```
如果只想同步一个仓库，那么可以用static_list（只同步列表中的）或者white_list（会校验仓库存在，如果不在则不创建）。

**Comment by WTxiaomage** [comment]
> 
![image](https://user-images.githubusercontent.com/20138139/143817563-c2a2ca82-5b82-494e-bb29-5195f401fa1f.png)
说我的秘钥对不正确吗，我是重新创建并且把秘钥设置在GitHub 中https://github.com/WTxiaomage/react-blog.git这个仓库，
公钥设置在gitee设置里面
一下是我的完整配置

name: Sync Github Repos To Gitee

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: Sync Github Repos To Gitee  # 名字随便起
      uses: Yikun/hub-mirror-action@v1.1  # 使用Yikun/hub-mirror-action
      with:
        src: github/WTxiaomage
        dst: gitee/WTxiaomage_admin
        white_list: react-blog
        static_list: react-blog

        dst_key: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}  # SSH密钥对中的私钥
        dst_token:  ${{ secrets.GITEE_TOKEN }}  # Gitee账户的私人令牌
#         account_type: org  # 账户类型
@yi-Xu-0100

**Comment by Yikun** [comment]
`secrets.GITEE_SSH_PRIVATE_KEY`，这个配置的有问题。

再次核对下哈：
1. github的secrets已经配置`GITEE_SSH_PRIVATE_KEY`为私钥内容(~/.ssh/id_rsa)。
2. 私钥所对应的公钥(~/.ssh/id_rsa.pub)，已经在这里配置：https://gitee.com/profile/sshkeys

**Comment by WTxiaomage** [comment]
> `secrets.GITEE_SSH_PRIVATE_KEY`，这个配置的有问题。
> 
> 再次核对下哈：
> 
> 1. github的secrets已经配置`GITEE_SSH_PRIVATE_KEY`为私钥内容(~/.ssh/id_rsa)。
> 2. 私钥所对应的公钥(~/.ssh/id_rsa.pub)，已经在gitee侧配置：https://gitee.com/profile/sshkeys
已经核对了，并且重新生成试过，还是不得行，遂放弃
请问你这个原理是啥子哦，我看日志是相当于有台154.213.2.253服务器，下载了GitHub的库，然后通过在仓库里面设置的GITEE_PRIVATE_KEY，往gitee上面推送代码吗？？？

**Comment by yi-Xu-0100** [comment]
@WTxiaomage Github action 相当于云服务器运行相应的代码。

**Comment by WTxiaomage** [comment]
![image](https://user-images.githubusercontent.com/20138139/143892303-bd7e3ac6-1263-461e-8478-f77e4342617b.png)
![image](https://user-images.githubusercontent.com/20138139/143892423-51ce6e44-7135-45c3-8cd3-a9e736470a26.png)
用大佬的配置复制过来并修改后试了，相应的公钥私钥都重新生成并替换，还是失败 @yi-Xu-0100 
![image](https://user-images.githubusercontent.com/20138139/143892682-3e54ab2d-e95c-4f6a-b80c-f35e0425fa9b.png)

**Comment by Yikun** [comment]
> 请问你这个原理啥子哦，我看日志是相当于有台154.213.2.253服务器，下载了GitHub的库，然后通过在仓库里面设置的GITEE_PRIVATE_KEY，往gitee上面推送代码吗？？？

action的服务器下载库，然后把private key写到服务器上，然后向gitee推送代码。

你也可以自己在秘钥所在机器做下测试，确保取秘钥的机器，能够向gitee push代码。

**Comment by Yikun** [comment]
从日志看，gitee_token没问题，下载也没问题，问题就出现在了push的时候，没权限。

**Comment by Yikun** [comment]
@WTxiaomage 你要不拿目前的配置同步一下另外一个仓试试？排除一下，是不是这个仓有敏感词之类的，被gitee拒了？

**Comment by WTxiaomage** [comment]
谢谢大佬，今天在重新试了一下成功了，不知道哪里出了毛病

**Comment by Yikun** [comment]
@WTxiaomage 恭喜恭喜。：）那我关闭issue了，有问题可以再开issue反馈。
