### ISSUE TITLE
突然间不能用配置文件未做修改

### ISSUE THREAD

**Issue by 21ki** [Yikun/hub-mirror-action#127]
# 从github同步到gitee

讲道理他是去拉github的仓库应该是谁都可以拉取的。https://github.com/21ki/win.git

配置文件如下
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source codes
        uses: actions/checkout@v1
      - name: Mirror Github to Gitee with white list
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/21ki
          dst: gitee/myki
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token:  ${{ secrets.GITEE_TOKEN }}
          clone_style: "ssh"
          white_list: "win"
          static_list: 'win'
          force_update: true
          debug: true

#  日志如下
Backup win
(1/3) Downloading...
Starting git clone git@github.com:21ki/win.git
Starting git clone git@github.com:21ki/win.git
Starting git clone git@github.com:21ki/win.git
(1/3) Downloading...
Starting git clone git@github.com:21ki/win.git
Starting git clone git@github.com:21ki/win.git
Starting git clone git@github.com:21ki/win.git
(1/3) Downloading...
Starting git clone git@github.com:21ki/win.git
Starting git clone git@github.com:21ki/win.git
Starting git clone git@github.com:21ki/win.git
Cmd('git') failed due to: exit code(128)
  cmdline: git clone git@github.com:21ki/win.git /github/workspace/hub-mirror-cache/win
  stderr: 'Cloning into '/github/workspace/hub-mirror-cache/win'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by yi-Xu-0100** [comment]
是 ssh 模式拉的，所以检查下 key 的权限。

**Comment by 21ki** [comment]
他来的是github的源仓库。没有可配置的地方啊

**Comment by Yikun** [comment]
下载的时候应该是默认是不需要权限。最近是不是改过什么配置？印象里开了two factor auth可能有影响。

Anyway，2种方法：
1. 改成默认的https模式，删除[1]或者指定为`https`
2. 把用于push到gitee的key，同时也配置到github上。（危险操作。源仓的key与目的仓的key相同，手误配置错了，会反向同步）

[1] https://github.com/21ki/win/blob/master/.github/workflows/gitee.yml#L17

**Comment by 21ki** [comment]
如果看时间线的话到时测试过GPG keys,会不会是这个问题

**Comment by Yikun** [comment]
@21ki 有可能 GPG keys机制没太了解过。简单说，原理就是把ssh-key要写到那个github action临时的计算资源上，如果需要额外的GPG配置，你可能也要通过某些action配置下或者hub-mirror-action本身支持GPG

**Comment by 21ki** [comment]
感觉应该是个bug，已经删除gpg keys  之后还是不行。然后我手动拉一遍然后在跑就可以了
```yaml
      - name: test
        run: |
          mkdir -p /opt/tmp && cd $_
          git clone https://github.com/21ki/win.git
```
感觉和gitlab runner的很像github action跑的时候拉取仓库会生成一个自己的token然后去跑，感觉这个token貌似不更新了。因为我测试GPG keys的时候曾经更新过github的ssh key，但是拉取github仓库模式是不需要的。先暂时这样

**Comment by Yikun** [comment]
好，解决了就好，issue先关了
