### ISSUE TITLE
请问我该怎么办才能同步到别人的仓库里

### ISSUE THREAD

**Issue by Alafun** [Yikun/hub-mirror-action#132]
具体来说，就是
 我想从 GitHub 拉取到自己的 GitHub 账号，然后同步到别人的 gitee 备份仓库（或者打一个 branch ）。可以实现吗，还是需要仓库主才可以做到

**Comment by yi-Xu-0100** [comment]
读取有读取的权限，写入有写入的权限，都有就行。

**Comment by Alafun** [comment]
> 

我需要先在 gitee 中 fork 别人的备份仓库吗

**Comment by Yikun** [comment]
> 我想从 GitHub 拉取到自己的 GitHub 账号，然后同步到别人的 gitee 备份仓库。

没看懂这句话。。。可以举例说明。@yi-Xu-0100 说的对，从哪同步就要读哪，同步到哪就要写哪。

**Comment by Alafun** [comment]
> 从哪同步就要读哪，同步到哪就要写哪。
@Yikun 我是从 GitHub 读取，然后在  gitee 上面写入

**Comment by Alafun** [comment]
> 没看懂这句话
意思就是 都不是 我本人的仓库，都是 别人的仓库

**Comment by Alafun** [comment]
#133 具体报错如下

**Comment by Yikun** [comment]
没办法同步到别人的仓库（因为你没有权限写）

**Comment by Alafun** [comment]
> （因为你没有权限写）

那我能 写到我特定的 `branch` 吗

**Comment by Yikun** [comment]
> 那我能 写到我特定的 `branch` 吗

目前只支持全分支同步，可以别名，比如github的A名的仓，同步到gitee的B名的仓。

**Comment by Alafun** [comment]
好的，我明白捏，谢谢你 @Yikun @yi-Xu-0100
