### ISSUE TITLE
Add AtomCI to Readme

### ISSUE THREAD

**Issue by Yikun** [Yikun/hub-mirror-action#136]
```
<a href="https://github.com/go-atomci/atomci/blob/master/.github/workflows/sync-to-gitee.yml"><img src="https://user-images.githubusercontent.com/1736354/147427763-301daf36-6edf-477b-a725-5174bb169d78.png"  width="90"></a>
```

https://github.com/Yikun/hub-mirror-action/issues/65#issuecomment-1000771233

@colynn AtomCI is using this action,

**Comment by Yikun** [comment]
![image](https://user-images.githubusercontent.com/1736354/147428228-f3e570a9-234c-4cef-a6c4-50e92a72aad2.png)

@colynn The original black ground logo looks like not very pretty.  and maybe you could **give a logo with white backgroud**, then I can display it in Readme.

**Comment by colynn** [comment]
How about this ? ![image](https://user-images.githubusercontent.com/5203608/147511617-ab8de8b2-8a87-4877-89da-2d9a400e4113.png)

Maybe you need resize the images, thanks

**Comment by Yikun** [comment]
![image](https://user-images.githubusercontent.com/1736354/147518814-4ea15f84-e70a-415e-942a-ea685ecbee43.png)

Added! @colynn Thanks for feedback!
