### ISSUE TITLE
建议实现  github release 同步到 gitee relase

### ISSUE THREAD

**Issue by KangLin** [Yikun/hub-mirror-action#140]
@Yikun 
国内访问GITHUB经常被墙。所以在国内做个镜像。

我的[项目](https://github.com/KangLin/)都使用了你的 gihub action 同步仓库到 gitee 。
但是目前，此 github action 不能同步 github release. 建议你加上此功能 😄

**Comment by Yikun** [comment]
感谢反馈，之前也有一些其他用户提到了这个功能，在这个问题记录：

https://github.com/Yikun/hub-mirror-action/issues/43

**Comment by Yikun** [comment]
@KangLin 先关了，有进展会在上面的issue更新
