### ISSUE TITLE
gitee 同步到 github, 把 github 的 action 的配置文件都覆盖没了

### ISSUE THREAD

**Issue by marlkiller** [Yikun/hub-mirror-action#141]
rt, 除了在 gitee 源头创建action配置文件外, 还有别的办法吗

**Comment by Yikun** [comment]
@marlkiller 

1. 在gitee侧也合入workflow文件
2. 在另外一个仓，同步其他仓，如果需要可以用black_list把不需要同步的仓禁掉。

**Comment by AdoShan** [comment]
> @marlkiller
> 
> 1. 在gitee侧也合入workflow文件
> 2. 在另外一个仓，同步其他仓，如果需要可以用black_list把不需要同步的仓禁掉。

可以支持库中的资源排除列表吗？例如GitHub同步到Gitee时排除掉.github/workflows

**Comment by Yikun** [comment]
@AdoShan 这个不支持，因为是基于commits的的同步。无法做到仓内文件的修改。

**Comment by AdoShan** [comment]
> @AdoShan 这个不支持，因为是基于commits的的同步。无法做到仓内文件的修改。

那可以在同步的时候设置排除文件嘛

**Comment by Yikun** [comment]
一样的，也不行。原因也是一样的，同步是基于commits的

**Comment by Yikun** [comment]
这个问题我先关了，挖个坑，支持基于rebase的mirror：https://github.com/Yikun/hub-mirror-action/issues/144
