### ISSUE TITLE
支持以.开始的repo

### ISSUE THREAD

**Issue by ShixiangWang** [Yikun/hub-mirror-action#145]
最近由于安装和使用一个github app需要，创建了一个仓库`.github`。这个在同步的时候出现了问题？是否有可能在未来加以支持？

```
Destination repo creating failed: {"error":{"name":["Name allows only chinese, 
letters, numbers, or an underscore (_), dash (-), periods (.), and plus (+),
 you must start with a letter or number as content, can not end with an 
underscore / underline, and its length is 2 to 191 characters"],
"path":["只允许包含字母、数字或者下划线(_)、中划线(-)、英文句号(.)，
必须以字母开头，且长度为2~200个字符"]}}
```

**Comment by Yikun** [comment]
@ShixiangWang 这个是gitee的限制。无法创建名字带.的仓库。

> 仓库名只允许包含中文、字母、数字或者下划线(_)、中划线(-)、英文句号(.)、加号(+)，必须以字母或数字开头，不能以下划线/中划线结尾，且长度为2~191个字符

![Screenshot_20220202_110126.jpg](https://user-images.githubusercontent.com/1736354/152086734-9d9ffeb3-b3ef-49ab-ba35-ed6b71a4d527.jpg)

你可以尝试用`mappings`参数，将源仓库映射为其他合法名字，进行同步:
```yaml
mappings: ".github=>github"
```

**Comment by ShixiangWang** [comment]
@Yikun 多谢！
