### ISSUE TITLE
yml文件语法错误

### ISSUE THREAD

**Issue by xuedaobian** [Yikun/hub-mirror-action#148]
您好我在使用这个action的时候，报了语法错误，这里是 [demo地址](https://github.com/xuedaobian/site-demo/actions/runs/1881991782/workflow)，我是copy来的，空格也存在，希望能得到你的帮助，谢谢

**Comment by xuedaobian** [comment]
通过校验工具校验完毕了

**Comment by Yikun** [comment]
是example的文档问题吗，还是您自己操作问题？如果有误，可以提PR修复文档，谢谢。
