### ISSUE TITLE
Error: Repository access blocked

### ISSUE THREAD

**Issue by appotry** [Yikun/hub-mirror-action#151]
yi-Xu-0100/repo-list-generator@v1.0.1
这个action的报错，搜索了一下，没有找到解决方案，猜测是个人仓库中由于某些repo被github封禁之后不能访问，导致的报错

目前只能不用这个action了，有人有解决方法么？

**Comment by appotry** [comment]
```
Run yi-Xu-0[10](https://github.com/appotry/hub-mirror-action/runs/5553067559?check_suite_focus=true#step:4:10)0/repo-list-generator@v1.0.1
  with:
    my_token: ***
    user: appotry/hub-mirror-action
    max_page: 10
    allow_empty: false
  env:
    dst_key: ***
  
    dst_token: ***
    gitee_user: ***
[INFO]: Usage https://github.com/yi-Xu-0100/repo-list-generator#readme
Get input value
Get repo list
  [INFO]: Successfully get repo data
  Error: Repository access blocked
```

**Comment by Yikun** [comment]
I guess you might want to raise issue in https://github.com/yi-Xu-0100/repo-list-generator/issues

cc @yi-Xu-0100

**Comment by yi-Xu-0100** [comment]
> I found that this error was related to a repository deleted but still in GitHub's database of all public repositories. To avoid this error I simply catched the exception and bypassed the broken record.
 _Originally posted by TestSMM in https://github.com/PyGithub/PyGithub/issues/1015#issuecomment-454527032_

我能找到的可能原因还有这一条。暂时我不太确定这该怎么绕过这个错误，可能得寻找更多的信息，等我有空的时候，我会尝试复现甚至修复这个问题。

**Comment by Yikun** [comment]
那这个问题我关了先~感谢！
