### ISSUE TITLE
同步的级别问题

### ISSUE THREAD

**Issue by RichardChan-Vietna** [Yikun/hub-mirror-action#153]
请问下，workflow 是放在某个项目的.github 底下么？那是不是意味着我们我发对组织下的所有项目进行更新，举例：一个组织下有项目A,B,C三个项目，是不是要在每一个项目下都创建workflow，并把**.yml 重新考呗到对应目录下，并修改仓库对应的路径才可以？ 有没有一种方法，就是在某个组织下建立一个wrokflow，并把yml文件放到这个目录下就能实现组织下任何仓库如果有变动都会同步更新到gitee中？能做到这样么？如果我的账户下有2个组织，2个组织下又有多个项目仓库，能否做到在用户级别只创建一个yml就能解决所有组织下的任何一个仓库如果有变动，都能及时更新到gitee中？这样就是最完美的了，期待您的回答。

**Comment by Yikun** [comment]
@RichardChan-Vietna 任何**一个**github的repo新增一个workflow即可，也无需放在需要同步的组织下(当然，也可以)。

同步是账号级别的，可以通过黑白名单来控制同步的仓库。

目前应该无法做到每个repo实时同步(除非放在每个repo下做push触发），主要是workflow没有组织级别的event。可以采用schedule来定期同步。demo可以参考主页里面展示的组织logo图片，每个图片点进去都是一个例子。

**Comment by RichardChan-Vietna** [comment]
感谢您的回答， 我还是有一点点不理解，您说同步是账号级别的，我这里举个例子 假如我的账号下有2个组织，Org1 和Org2，
在Org1下有
          +Org1-repo1, 
          +Org1-repo2, 
在Org2下有
          +Org2-repo1, 
          +Org2-repo2,
此事我只把yml的配置配置在Org1-repo1 下面 其他都把配置，那么
是否我在更新Org1-repo1的时候，Org1-repo2如果也有变动，是否也能同步到Gitee中呢？
如果不行，那怎么说是账户级别的同步呢？

另外还有一个问题，你说的放在组织下也可以，具体要怎么弄？。
我期待的完美结果还是只在账户下配置一个yml（这个账户下有很多组织，组织下又有很多repo的情况），任何一个repo有变动，都能同步到gitee中。

**Comment by Yikun** [comment]
> 此时我只把yml的配置配置在Org1-repo1 下面 其他都没有做配置，那么
是否我在更新Org1-repo1的时候，Org1-repo2如果也有变动，是否也能同步到Gitee中呢？

在repo1触发的时候会同步repo2，但是触发的时间要跟着repo1去走，所以推荐你在repo1启用schedule触发周期同步。

**Comment by Yikun** [comment]
> 另外还有一个问题，你说的放在组织下也可以，具体要怎么弄？。

新建一个repo-mirror，在这个仓里，做同步repo1, repo2的事情。

**Comment by Yikun** [comment]
> 我期待的完美结果还是只在账户下配置一个yml（这个账户下有很多组织，组织下又有很多repo的情况），任何一个repo有变动，都能同步到gitee中。

目前github未提供这个机制。

**Comment by RichardChan-Vietna** [comment]
好的，非常感谢你的回答。
