### ISSUE TITLE
超时未自动停止

### ISSUE THREAD

**Issue by Yang-Xijie** [Yikun/hub-mirror-action#156]
您好，我使用这个项目来同步我的个人GitHub仓库到Gitee
第一次同步进行了46min还未结束 我就手动cancel掉了
一看发现设置的timeout是30min 但是并没有自动停止
而且卡在了安装完毕后的地方
请问这可能是什么原因造成的呢？
<img width="1237" alt="Xnip2022-04-27_19-05-20" src="https://user-images.githubusercontent.com/57952362/165505249-6b98eefd-a23a-4f4d-8a79-722883578f51.png">
<img width="1166" alt="Xnip2022-04-27_19-05-26" src="https://user-images.githubusercontent.com/57952362/165505262-e3fbbbca-9433-4389-9123-171d537ebc79.png">

**Comment by Yang-Xijie** [comment]
只同步单一仓库是没有问题的 `static_list: "C-Makefile-template"` 很快就能完成

**Comment by yi-Xu-0100** [comment]
@Yang-Xijie 从图片看，这个 action 还处于构建状态，也就不会触发脚本内部关于参数的使用。可能是 github 的问题，建议再尝试。有的时候 github 就是会抽风，

可以给出对应的链接看看情况。

**Comment by Yang-Xijie** [comment]
我知道了是我只给单一仓库加了 GITEE_PRIVATE_KEY 和 GITEE_TOKEN。想知道如何给个人账户添加这些值呢？我打算同步所有的仓库…但是在GitHub的设置中好像并没有找到
```
cmdline: git push -f gitee refs/remotes/origin/*:refs/heads/* --tags --prune
[408](https://github.com/Yang-Xijie/Gitee-Mirror/runs/6192457977?check_suite_focus=true#step:3:408)
  stderr: 'Load key "/root/.ssh/id_rsa": error in libcrypto
[409](https://github.com/Yang-Xijie/Gitee-Mirror/runs/6192457977?check_suite_focus=true#step:3:409)
git@gitee.com: Permission denied (publickey).
[410](https://github.com/Yang-Xijie/Gitee-Mirror/runs/6192457977?check_suite_focus=true#step:3:410)
fatal: Could not read from remote repository.
```

**Comment by Yang-Xijie** [comment]
感谢！我再自己研究一下！

**Comment by Yang-Xijie** [comment]
看起来是我有一个fork的仓库 然后卡在这里了
使用`yi-Xu-0100/repo-list-generator@v1.0.1`就没问题了

**Comment by Yikun** [comment]
说明下，这个超时时间指的是单个git操作话费时间，不是总时间。
