### ISSUE TITLE
使用hub-mirror-action 一直处于运行状态

### ISSUE THREAD

**Issue by h7ml** [Yikun/hub-mirror-action#157]
#### 1. 描述问题：

今天使用 https://github.com/Yikun/hub-mirror-action action会一直在运行状态

#### 2. 复现地址：

 https://github.com/dgiot/dgiot/runs/6500429421?check_suite_focus=true

猜测可能和gitee最近的政策有关

**Comment by Yikun** [comment]
@h7ml 似乎是偶现的？现在好了吗

**Comment by h7ml** [comment]
感谢，这个确实是偶现的，这几天都没用出现了
