### ISSUE TITLE
希望添加清理缓存的功能

### ISSUE THREAD

**Issue by wlccgp3** [Yikun/hub-mirror-action#166]
由于同步org仓库列表很大，自建的runner磁盘满了
fork的改动很大，就不提交合并请求了，这里只截取部分代码
yml
```yml
force_clean: true
```

mirror.py
```python
    def clean(self):
        if self.force_clean:
            print("Force Clean...")
            shutil.rmtree(self.repo_path, True)

```

**Comment by wlccgp3** [comment]
日志打印问题，默认缓存是绝对路径，repo_path已经是绝对路径了，显示成了/github/workspace/github/workspace/hub-mirror-cache
```
        print("Clone completed: %s" % os.getcwd() + self.repo_path)
```
个人建议，可以用`CUR_DIR = Path(__file__).resolve().parent`来解析

**Comment by Yikun** [comment]
@wlccgp3 可以提个PR。就是同步完，把本地路径清理了，对吧？

**Comment by wlccgp3** [comment]
我这边魔改了很多东西，就是同步完，清理仓库

**Comment by Yikun** [comment]
git checkout -b xxx

创建一个新的分支即可
