### ISSUE TITLE
希望增加打印已成功仓库日志

### ISSUE THREAD

**Issue by wlccgp3** [Yikun/hub-mirror-action#167]
因为github job默认6小时限制，org仓库列表非常大的情况下，容易中断且不知道哪些已经同步了，可以在遍历src_repos的时候，每次都打印所有已成功仓库，用`,`分隔，这样可以直接复制到black_list

另外一个想法是，用一个缓存文件来记录已同步的仓库，如果需要重新同步只需删除那个缓存文件

**Comment by wlccgp3** [comment]
想到另外一个解决办法，增加一个参数，获取目的org仓库列表作为black_list

**Comment by wlccgp3** [comment]
我这里是已经知道需要的仓库列表，如果是org列表，可以自行请求对应src获取所有的仓库列表
比如gitee有直接测试的url，https://gitee.com/api/v5/swagger#/getV5ReposOwnerRepoStargazers?ex=no

终极解决方案，脚本创建多个job：

```python
# -*- coding: utf-8 -*-
from xml.etree.ElementTree import parse
from pathlib import Path
import numpy as np

CUR_DIR = Path(__file__).resolve().parent

doc = parse(CUR_DIR.joinpath('default.xml'))

dst_repos = []
projects = doc.findall('project')
for item in projects:
    if item.get('remote') is None:
        dst_repos.append(item.get('name'))

# print(','.join(dst_repos))

head = '''
on:
  workflow_dispatch:
  push:

name: khadas-org-mirror
jobs:
'''

tpl = '''
  job{0}:
    name: job{0}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v1
    - name: Mirror Github to Gitee
      uses: ./.
      with:
        src: github/khadas
        dst: gitee/spectre_khadas
        dst_key: ${{{{ secrets.GITEE_PRIVATE_KEY }}}}
        dst_token: ${{{{ secrets.GITEE_TOKEN }}}}
        static_list: "{1}"
        clone_style: ssh
        account_type: org
        force_update: true
        force_clean: true
        timeout: '2h'
        debug: true

'''

with CUR_DIR.parent.joinpath('.github/workflows/khadas-org.yml').open('w', encoding='utf-8') as f:
    f.write(head.lstrip('\n'))

    items = np.array_split(dst_repos, 30)
    for index, item in enumerate(items):
        f.write(tpl.lstrip('\n').format(index+1, ','.join(item)))
```

**Comment by Yikun** [comment]
github action每次的job应该是无状态的，所以，用有状态列表可能不是很好。

如果是因为仓库非常大引起的话，是不是可以尝试对大仓库加个warning？

**Comment by Yikun** [comment]
https://github.com/Yikun/hub-mirror-action#%E6%8C%87%E5%AE%9A%E7%9B%AE%E5%BD%95cache

加缓存可以解决问题吗？一定程度上减少每个仓库处理的时间

**Comment by Yikun** [comment]
另外，按照https://github.com/Yikun/hub-mirror-action/issues/167#issuecomment-1305375871 的思路，你还可以考虑加一个单独的task，用来生成github action matrix。然后matrix传进去，自动生成多个job

**Comment by wlccgp3** [comment]
哦哦，我之前一直用的gitlab，我都是边看文档边改的

**Comment by Yikun** [comment]
@wlccgp3 https://stackoverflow.com/questions/70990637/how-to-convert-string-to-array-and-put-it-in-github-actions-matrix

类似这种思路

**Comment by wlccgp3** [comment]
好的，感谢，不过我还是用我现在的这种方式吧，除非封装到python模块里，用参数来控制，否则我感觉这种暴力的方式还更快点
