### ISSUE TITLE
hub_mirror-action@v运行缓慢

### ISSUE THREAD

**Issue by SWHL** [Yikun/hub-mirror-action#171]
- 感谢作者的工作，用了好久hub-mirror-action，很好用，点赞
- 最近不知为啥，使用最新`Yikun/hub-mirror-action@v1.2`，运行时间很长，希望可以看一下是不是bug
- 运行的yml脚本：[SyncToGitee.yml](https://github.com/RapidAI/RapidOCR/blob/main/.github/workflows/SyncToGitee.yml)
- 运行的job详情：[Update hub-mirror-action version to 1.2 #73](https://github.com/RapidAI/RapidOCR/actions/runs/3908787107/jobs/6679219718)

在我写issue时，action已经运行了11分钟了。

**Comment by Yikun** [comment]
@SWHL 看了下日志，主要时间花在在构建镜像上了，应该是github action和ubuntu间的网络问题。只能再等等了😂

**Comment by SWHL** [comment]
嗯呢，感谢回复。
