### ISSUE TITLE
同步目标源时创建仓库返回502

### ISSUE THREAD

**Issue by lzm0x219** [Yikun/hub-mirror-action#173]
<img width="733" alt="image" src="https://user-images.githubusercontent.com/50414099/218701309-ad68f6d4-b795-4b01-b8e3-b1ab01393549.png">

pro-components在gitee是没有的，调用gitee的创建接口报错了。。

**Comment by Yikun** [comment]
这个似乎是gitee api不稳定引起的问题，先关闭了。
