### ISSUE TITLE
error in gitee 同步github

### ISSUE THREAD

**Issue by rainoffallingstar** [Yikun/hub-mirror-action#179]
https://github.com/rainoffallingstar/.cli-bot/actions/runs/5555216732/jobs/10146056737
Cmd('git') failed due to: exit code(128)
  cmdline: git clone https://gitee.com/rainoffalingstar/DLBL-methyarrary.git /github/workspace/hub-mirror-cache/DLBL-methyarrary
  stderr: 'Cloning into '/github/workspace/hub-mirror-cache/DLBL-methyarrary'...
fatal: could not read Username for 'https://gitee.com/': No such device or address'

可能是ssh在生成过程中存在一些权限问题？

**Comment by Yikun** [comment]
https://gitee.com/rainoffalingstar/DLBL-methyarrary

是私有仓？目前不支持

**Comment by rainoffallingstar** [comment]
感谢，发现了，解决了
