### ISSUE TITLE
如何从 github 个人账户的一个项目同步到gitee的组织下的一个项目？

### ISSUE THREAD

**Issue by ElderJames** [Yikun/hub-mirror-action#22]

**Comment by Yikun** [comment]
@ElderJames 暂不支持，建议在github上建个组织吧

**Comment by ElderJames** [comment]
我用了另一个，搞定了，谢谢😜

**Comment by Yikun** [comment]
看了下，用的是这个：https://github.com/wearerequired/git-mirror-action

后面看到这个issue有需要的同学可以参考参考。

hub-mirror-action主要的功能还是批量同步，如果有需要做单repo同步的，可以用git-mirror-action插件。：）
