### ISSUE TITLE
怎样配置公钥？

### ISSUE THREAD

**Issue by ShixiangWang** [Yikun/hub-mirror-action#30]
我想将 GitHub 仓库同步到 Gitee 上，但容器中 Push 代码报出无权限问题。我看到它使用的是容器 root 的公钥，很奇怪。我已经在GitHub 仓库中配置了说明中的密钥 

![image](https://user-images.githubusercontent.com/25057508/87247803-a1f4e900-c488-11ea-8903-732c41bc14a2.png)

![image](https://user-images.githubusercontent.com/25057508/87247860-e7b1b180-c488-11ea-8b4c-adba8937ed9e.png)

也检查过可以连接。

```r
wsx@zd:~$ ssh git@gitee.com
The authenticity of host 'gitee.com (212.64.62.174)' can't be established.
ECDSA key fingerprint is SHA256:FQGC9Kn/eye1W8icdBgrQp+KkGYoFgbVr17bmjey0Wc.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'gitee.com,212.64.62.174' (ECDSA) to the list of known hosts.
Hi 王诗翔! You've successfully authenticated, but GITEE.COM does not provide shell access.
Connection to gitee.com closed.

```

问题出在容器没有使用我提供的公钥，是我配置哪里有问题吗？

祝好，
诗翔

**Comment by Yikun** [comment]
GITEE_PRIVATE_KEY配置的是**私钥**，也就是你wsx的根目录的~/.ssh/id_rsa，这个文件，另外，也需要保障这个私钥所对应的公钥已经可以访问Gitee。

**Comment by ShixiangWang** [comment]
@Yikun 谢谢，我理解了，试一试

**Comment by ShixiangWang** [comment]
![image](https://user-images.githubusercontent.com/25057508/87263589-35add000-c4f0-11ea-9c51-11b8c44a7f1e.png)

这次在第二步转了很久，显示秘钥不对，我是把包括BEGIN 到 END的所有内容拷贝进去了，是不是只要 BEGIN和END中间的？

![image](https://user-images.githubusercontent.com/25057508/87263624-52e29e80-c4f0-11ea-98bb-d588522c339b.png)

**Comment by ShixiangWang** [comment]
显示成功了，谢谢。这个action很nice
