### ISSUE TITLE
迁移仓库至hub-mirror-action组织

### ISSUE THREAD

**Issue by Yikun** [Yikun/hub-mirror-action#40]
目前，越来越多的仓库在使用这个工具，例如

- https://github.com/kunpengcompute
- https://github.com/opengauss-mirror
- https://github.com/openeuler-mirror
- https://github.com/mindspore-ai

为了后续演进，我们可以将仓库迁移至 https://github.com/hub-mirror-action ，这样可能更利于演进。

**Comment by yi-Xu-0100** [comment]
我在使用这个 action 时，创建了一个 [模板仓库 - hub-mirror](/yi-Xu-0100/hub-mirror) 方便作为使用样例，不知道能否加入组织中，这样只需要使用这个模板创建仓库，并修复部分参数，即可直接使用这个仓库去管理。

当然因为还在测试中，暂时未编写相关的 readme 文件去指明需要修复哪些参数，加入组织后，我想可以有更多的人来完善这个通用模板，方便使用和配置。

**Comment by Yikun** [comment]
@yi-Xu-0100 感谢反馈，这个建议很赞，测试完善后，欢迎贡献。

**Comment by yi-Xu-0100** [comment]
我创建的 [模板仓库 - hub-mirror](/yi-Xu-0100/hub-mirror) 已经基本完善，可以在 readme 中添加我的仓库作为同步 GitHub 到 Gitee 的使用参考链接嘛~

**Comment by Yikun** [comment]
@yi-Xu-0100 才看到这个消息，下次可以直接提PR哈~

**Comment by Yikun** [comment]
暂时不迁移了，感觉目前暂时没什么必要。后续需要的时候再reopen吧
