### ISSUE TITLE
同步空仓库会暂停同步过程

### ISSUE THREAD

**Issue by yi-Xu-0100** [Yikun/hub-mirror-action#56]
我似乎有个老旧的空仓库，MyWiki，在同步过程中报错并直接退出。

```
(1/3) Updating...
Your configuration specifies to merge with the ref 'refs/heads/master'
from the remote, but no such ref was fetched.
Update failed
(2/3) Importing...
load pubkey "/root/.ssh/id_rsa": invalid format
No refs in common and none specified; doing nothing.
Perhaps you should specify a branch such as 'master'.
Connection to gitee.com closed by remote host.
error: failed to push some refs to 'git@gitee.com:yiXu0100/MyWiki.git'
 Push failed 
```

链接: <https://github.com/yi-Xu-0100/hub-mirror/runs/1252957338>

**Comment by Yikun** [comment]
看着不应该退出，很奇怪，开个debug跑个日志我看看？

**Comment by yi-Xu-0100** [comment]
我重跑了下，发下是卡住等待了许久似乎，我重新在 test 中试验下啊

**Comment by yi-Xu-0100** [comment]
刚刚尝试了重启 list 列表中有空仓库的方式测试是否暂停。 发现还没有到这个空仓库。好像就触发限流了。

链接：<https://github.com/yi-Xu-0100/hub-mirror/runs/1258503933>

 不知道对这种状况有没有好的反馈啥的。而不是跑了一小时……

**Comment by yi-Xu-0100** [comment]
我取消了 action ，这个是 log: <https://gist.github.com/yi-Xu-0100/5cdd096a2c38cc693df63a831e8b9872>

**Comment by yi-Xu-0100** [comment]
我发现了，和 #57 一个原因……我的版本未升级，升级之后没问题了……😭

只不过上面的回复中，超时问题确实存在，不过超时一定程度，GitHub会帮助关闭应该，倒是不用担心……😎
