### ISSUE TITLE
创建仓库的部分多余信息考虑作为 debug 输出

### ISSUE THREAD

**Issue by yi-Xu-0100** [Yikun/hub-mirror-action#57]
我是用 balck_list 去除了这个空仓库后，能够全部完成同步，但是最后没有统计信息，不知道怎么回事。是否可以将统计信息作为输出值，这样让下一个步骤获取后，echo 出来。

链接 :<https://github.com/yi-Xu-0100/hub-mirror/actions/runs/306356282>

---

gitee 中未存在的仓库，创建过程会在 log 中输出一大段内容，是否应该作为 debug 输出？

![image](https://user-images.githubusercontent.com/25523606/95984900-78b47200-0e56-11eb-97c2-8f9154f3a6c9.png)

**Comment by Yikun** [comment]
恩，这些信息可以直接干掉。后面对所有的curl加下-s和重定向

curl **-s** xxx **> /dev/null**

**Comment by yi-Xu-0100** [comment]
我的持续观察中，会在这个空仓库的地方卡个5分钟以上，然后结束。
空仓库为最后一个：<https://github.com/yi-Xu-0100/test/runs/1258278948>
空仓库不是最后一个：<https://github.com/yi-Xu-0100/test/runs/1258327855>
两个我都是开了 action 中的 debug 参数。
似乎在很少repo 的情况下触发不了，等会我再给出多 repo 同步的内容。

**Comment by Yikun** [comment]
好像回复错地方了？是想回复这个吗 https://github.com/Yikun/hub-mirror-action/issues/56

**Comment by yi-Xu-0100** [comment]
@Yikun 确实，我发现没有输出可能是版本问题，当时仓库未使用最新版……
