### ISSUE TITLE
请问支持github与gitee仓库的一对一同步吗

### ISSUE THREAD

**Issue by sculpta** [Yikun/hub-mirror-action#6]
只同步github的test仓库和gitee的test仓库

**Comment by Yikun** [comment]
@sculpta 暂不支持，github到gitee的同步，可以使用gitee的导入功能。

**Comment by sculpta** [comment]
> @sculpta 暂不支持，github到gitee的同步，可以使用gitee的导入功能。

好，谢谢！

**Comment by Yikun** [comment]
FYI, 0.7之后的版本就支持了，https://github.com/Yikun/hub-mirror-action/releases/tag/v0.07
