### ISSUE TITLE
同步时，Github和Gitee的仓库名可否不同？

### ISSUE THREAD

**Issue by JasonkayZK** [Yikun/hub-mirror-action#64]
如题。如果github中的名称是aaa，要同步到gitee的仓库为bbb。
这种情况能否实现呢？谢谢解答！

**Comment by yi-Xu-0100** [comment]
见 https://github.com/Yikun/hub-mirror-action/issues/45#issuecomment-708956774

**Comment by Yikun** [comment]
@JasonkayZK 对的，可以参考楼上链接，目前还不支持，后续可能会考虑用`mapping`来实现。

**Comment by JasonkayZK** [comment]
好的，我尝试一下。
希望能加mapping的功能啊。很赞！♥

**Comment by uuz** [comment]
希望可以添加类似prefix、suffix，
prefix在未指定且启用改名时默认以用户名为前缀
这样就可以避免同步多个用户可能导致同名的问题

**Comment by yi-Xu-0100** [comment]
@uuz maping 会要求设置一对键值，如果没有设置的，会同步失败，应该不会出现，未指定的情况，还成功覆盖同步了

**Comment by Yikun** [comment]
感谢大家的关注和反馈。代码已Merge到主干~
