### ISSUE TITLE
Operation timed out 能否优化流程

### ISSUE THREAD

**Issue by yi-Xu-0100** [Yikun/hub-mirror-action#69]
有时会触发 `Operation timed out`, 造成同步失败，是否能够对此也提示 warning，并对结果设置通过，一般这种第二天同步会没有问题，但是偶尔地触发显得这个是有 bug 一样。排查之后却发现只是请求失败了。

或者对该仓库的同步在最后重新请求一遍，如果两次都不通过，则设置失败。

见： <https://github.com/yi-Xu-0100/hub-mirror/runs/1316299550>

**Comment by Yikun** [comment]
@yi-Xu-0100 最近我也遇到类似问题了，昨天开始已经试着加这个功能了。解决这个问题需要2个修改点：
1. **超时失败。**为git的指令增加timeout的参数例如：
```
timeout 30 git pull -p # 30秒后失败
```
2. **失败后重试。**因超时引起的失败，进行重试。

目前，这个超时失败这个我已经在[1]做了，失败重试也会在最近加进来。

[1] https://github.com/Yikun/hub-mirror-action/tree/paging

**Comment by yi-Xu-0100** [comment]
我看到有时请求目的端的仓库是否创建也会 timeout ，然后会尝试 `Create non-exist repo...` ，这里是否应该直接选择创建仓库，并判断返回信息，是否包含 `{"error":{"base":["已存在同地址仓库（忽略大小写）"]}}`，这样少了一个可能的请求，而且并不会对流程有影响。

**Comment by Yikun** [comment]
> 我看到有时请求目的端的仓库是否创建也会 timeout ，然后会尝试 Create non-exist repo... ，这里是否应该直接选择创建仓库，并判断返回信息，是否包含 {"error":{"base":["已存在同地址仓库（忽略大小写）"]}}，这样少了一个可能的请求，而且并不会对流程有影响。

这个是 https://github.com/Yikun/hub-mirror-action/issues/66 引起的问题，在https://github.com/Yikun/hub-mirror-action/commit/5d45527f48d6e1ec4922c152fa93e67296526ddd fix了
