### ISSUE TITLE
删除默认分支后，从 cache 中无法成功拉取

### ISSUE THREAD

**Issue by yi-Xu-0100** [Yikun/hub-mirror-action#78]
![image](https://user-images.githubusercontent.com/25523606/97935349-4641c900-1db3-11eb-8ca0-64b2826e3070.png)

由于我的 GitHub 的仓库删除了默认仓库，但是 Gitee 中也是默认仓库，同步后，无法完成删除操作，但是似乎由于顺序问题，对于其他分支的同步也无法完成。

我在 Gitee 上，无法找到 main 分支，也就没法切换默认分支，来完成重新同步。

我记得在 #39 中我提到了相关顺序问题，现在发现并不一定能够保证新建分支的顺利完成，是否后面会支持保证完成分支建立的过程？

GitHub 地址: <https://github.com/yi-Xu-0100/Learn-for-coding>
Gitee 地址: <https://gitee.com/yiXu0100/Learn-for-coding>

PS: 我已经使用 v0.11 的版本，#39指代的链接定位的文件发生了变化，我也不知道当时所指代的位置了。

**Comment by yi-Xu-0100** [comment]
我发现似乎是这个拉取出现问题，而不是同步出现问题。

https://github.com/Yikun/hub-mirror-action/blob/cf027c394e684810683705528b53de53ef6aeaab/entrypoint.sh#L173

这里的拉取应该是因为本地的 cache 分支是 master，造成无法删除当前的分支，然后无法拉取成功。

**Comment by Yikun** [comment]
@yi-Xu-0100 哈哈，你又踩坑了，这问题我也遇到过类似的。

这个问题的本质是cache的数据有问题（比如分支变化，无法自动merge；再比如）导致的，规避方法是换下cache的key。

其实，在push的时候，当时也有类似的问题。但是，可以通过force update解决。

但这个pull，目前git是没有（或者是我不知道）git pull -f之类的指令的，所以可能的解决方案是：

方案一：在git pull失败的时候，通过reset之类的把本地的错误修改回退。
方案二：在git pull失败的时候，干掉文件夹，重新clone一份

即保证本地cache纯净后，再进行同步。

**Comment by yi-Xu-0100** [comment]
```bash
git clone --reference[-if-able] 
```

刚查了下，使用方案二感觉会好些，可以用上面的参数，应该还能利用一下 cache 的数据。具体能利用多少就不知道了，但我想能够对大仓库还是能够提高下载速率的。

方案一的话，感觉并不是需要同步的时候考虑，当然仅是在强制同步的情况下。

**Comment by yi-Xu-0100** [comment]
我使用了简单的解决办法。我删除 cache 中的错误的对应仓库的文件夹，使用这个步骤在备份的步骤之后。
```yaml
- name: delete block_list cache directory
  run: |
    rm -rf ${{ github.workspace }}/hub-mirror-cache/Learn-for-coding/
```
注意事项：
1. 此时需要将这个仓库加入 `black_list` 。在完成后，再重新将这个仓库移除 `black_list` 
2. 注意此时的 `cache_path` 应该为 `/github/workspace/hub-mirror-cache`

步骤有点繁琐，但可以在出现问题的时候，通过两次提交来完成修复这个这个同步问题，而不需要添加单独的同步文件来对该仓库处理。

**Comment by Yikun** [comment]
在Python分支里面，已经解决了这个问题，如果更新失败则会删除旧代码，重新clone一份：

https://github.com/Yikun/hub-mirror-action/blob/1c5777f61ac141a7a7c64f4ac71f6db86e66cd56/hubmirror.py#L69-L75

欢迎使用：`uses: Yikun/hub-mirror-action@python`体验，后续stable后也会merge主干分支。
