### ISSUE TITLE
仓库的 commit 记录被修改后无法成功从 cache 文件夹拉取最新记录

### ISSUE THREAD

**Issue by yi-Xu-0100** [Yikun/hub-mirror-action#82]
```log
Backup learn-scripts ...
(0/3) Downloading...
Create non-exist repo...
fatal: remote gitee already exists.
Remote already exists.
(1/3) Updating...
From https://github.com/yi-Xu-0100/learn-scripts
 + c31e8a4...f4173f2 main       -> origin/main  (forced update)

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.
```

同一个任务中的其他仓库能够完成备份。

任务链接：<https://github.com/yi-Xu-0100/hub-mirror/runs/1525624122>

更多可能的信息，该仓库是本地新建的并初始化的。然后添加 GitHub 仓库为远程库，并推送到 GitHub 中。

最开始的几次记录时成功备份的。

错误记录从，我有一次使用 rebase 命令修改了最后一次的 commit 描述，并强制同步到 GitHub 中。

可以看出，同步该仓库时，GitHub 强制拉取最新更新出现问题。

**Comment by yi-Xu-0100** [comment]
疑似是 #78 的同类型 bug，在拉取时，由于 cache 的存在和最新的仓库不一致导致的问题。

https://github.com/Yikun/hub-mirror-action/blob/45a8476886e50735e2bfbf1fa1affb4aee5806df/entrypoint.sh#L170-L174

**Comment by Yikun** [comment]
嗯，一样的问题，遇到此类情况，暂时规避方法是先把cache去掉，或者cache换个名字。

最终方案和 #78 类似吧，pull失败重新clone。
