### ISSUE TITLE
Python重写hub-mirror-action

### ISSUE THREAD

**Issue by Yikun** [Yikun/hub-mirror-action#88]
各式各样的实际且潜在的需求 [1]，让hub-mirror-action维护和演进越来越不便，可读性也越来越差 [2]，这个action已经不再是一个简单的同步脚本了，而是支持着很多参数、功能的action同步服务。

所以，我希望**用Python重写hub-mirror-action**。

1. **[必选]** 当然，保持所有参数的兼容性是底线。
2. **[必选]** 我将会建一个python的分支，来实现，stable后，再merge到主干。
3. **[可选]** 此刻，突然产生一个想法，我们是不是可以把hub-mirror-action封装为一个py lib，这样，即使脱离了github action也能很快的用起来，更有助于调测？

[1] https://github.com/Yikun/hub-mirror-action/issues
[2] https://github.com/Yikun/hub-mirror-action/blob/master/entrypoint.sh#L230-L236
[3] https://github.com/Yikun/hub-mirror-action/blob/cf027c394e684810683705528b53de53ef6aeaab/action.yml

**Comment by Yikun** [comment]
cc @yi-Xu-0100 @ouuan @ShixiangWang @Ir1d @21ki @JasonkayZK

希望得到你们的建议。：）

**Comment by yi-Xu-0100** [comment]
@Yikun actions 的官方的库多数是 JavaScript，如果用 JavaScript 是否对日志和参数更友好。

**Comment by Yikun** [comment]
@yi-Xu-0100 Javascript不是我的“母语”。哈哈，维护起来难度就更大了。

**Comment by JasonkayZK** [comment]
支持使用python改，使用python + 配置的形式我觉得会更方便；

**Comment by yi-Xu-0100** [comment]
@Yikun 可以的，这样的话整体的改动少

**Comment by Yikun** [comment]
@JasonkayZK 
> 支持使用python改，使用python + 配置的形式我觉得会更方便；

配置指的是？需要给py来个单独的/etc/hubmirro.ini这种？还是类似命令行参数配置支持？

**Comment by yi-Xu-0100** [comment]
@Yikun 我主要是对 JavaScript 官方库中对输出的日志整合的部分感觉很好。所以如果对当前项目来说，可能不太有必要强行使用，以维护成本最小为主就好。

后续有需要和空闲的话，我个人可能会重构一个 JavaScript 的 action 版本，做个轮子试试手看看效果😁

**Comment by ShixiangWang** [comment]
很棒，支持哈。

**Comment by JasonkayZK** [comment]
> @JasonkayZK
> 
> > 支持使用python改，使用python + 配置的形式我觉得会更方便；
> 
> 配置指的是？需要给py来个单独的/etc/hubmirro.ini这种？还是类似命令行参数配置支持？

我说的是配置文件的形式，如果有命令行当然更好；

**Comment by Yikun** [comment]
Python版本代码已处于基本可用状态：https://github.com/Yikun/hub-mirror-action/pull/90

可以使用以下yml的版本试用：
```
uses: Yikun/hub-mirror-action@python
```

目前Python版代码的核心类包括：
- HubMirror：用于控制整提流程，处理黑白名单
- Mirror：用于处理git clone，git push，git pull等操作。
- Hub：用于请求github、gitee API，例如创建仓库、获取仓库列表等。

python代码现在还都在一个文件里，后面会拆开。

**Comment by Yikun** [comment]
There are many orgnazaition start to test the python version:

openLooKeng: https://github.com/openlookeng/sync-config/pull/3
openEuler: https://github.com/openeuler-mirror/sync-config/pull/17
openGauss: https://github.com/opengauss-mirror/sync-config/pull/12
MindSpore: https://github.com/mindspore-ai/infrastructure/pull/57
Kunpeng: https://github.com/kunpengcompute/Kunpeng/pull/66
Ascend: https://github.com/Ascend/infrastructure/pull/7

**Comment by Yikun** [comment]
经过上述的几个repo的测试，我觉得已经可以达到合并到主干的要求，如果没有其他问题，我打算在本周内把python分支合入的主干。

**Comment by ShixiangWang** [comment]
厉害厉害，合并后无需改变之前的调用代码是吗？https://github.com/ShixiangWang/sync2gitee/blob/bc0735d0509353bfd50dd21346a109f9974b2a71/.github/workflows/auto-sync.yml#L16

**Comment by Yikun** [comment]
@ShixiangWang 是的，无需改变，前项兼容的。

另外，你也可以现在提前体验下，把你的配置换为`uses: Yikun/hub-mirror-action@master` ==> `uses: Yikun/hub-mirror-action@python`，因为我看你已经开启了on push在master，所以提个PR在你那个同步仓，即可触发，不用合入。

**Comment by ShixiangWang** [comment]
好的，非常感谢哈～
