### ISSUE TITLE
关于在Github与Gitee之间同步代码的问题

### ISSUE THREAD

**Issue by DoveBoy** [Yikun/hub-mirror-action#89]
请教作者，如何使用Github Action拉取gitee私有库的代码同步到自己的仓库下？只有gitee私有库的id_rsa，具体应该怎么操作？盼望解答。

**Comment by yi-Xu-0100** [comment]
#38 可能得等待支持

**Comment by MisterGlasses** [comment]
要实现这个 是不是还要再加个src_key src_token

**Comment by Yikun** [comment]
@MisterGlasses 恩，是的。

src_token用来获取源列表，
src_key用来git clone

然后，git clone 的时候还需要用specific key去clone(因为默认的ssh key已经是dst_key了)。[1]

[1] https://stackoverflow.com/questions/4565700/how-to-specify-the-private-ssh-key-to-use-when-executing-shell-command-on-git
