### ISSUE TITLE
新增skip_exit参数，控制退出流程

### ISSUE THREAD

**Issue by Yikun** [Yikun/hub-mirror-action#96]
在 https://github.com/Yikun/hub-mirror-action/issues/62 讨论的时候，我们发现了一个潜在需求。

目前实现，如果有failed_list，会直接以exit code 1退出，最终导致任务失败。

这样可能会影响到后续其他流程的job，所以，如果一个用户需要在hub-mirror-action同步失败的情况下，job也不退出的话，那么可以新增一个参数来控制。

- 默认，skip_exit为false时，job会根据同步情况进行退出。
- skip_exit为true时，job永远会成功。

不过这个需求，我觉得应该是写workflow的人控制的，我猜github action本身应该有个什么参数也可以在workflow控制一下？

**Comment by yi-Xu-0100** [comment]
@Yikun actions 中有一定的检查状态的表达式。见 https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#job-status-check-functions

**Comment by Yikun** [comment]
Yep，就是这个，那我觉得这个需求优先级就更低啦，没什么没必要了~

**Comment by Yikun** [comment]
这个问题关了，我觉得目前的方式可能更好，尽力同步所有错误，删除失败的错误即可。

如果后续还有job不想受到job的影响，可以用stratages去控制，也可以用`if: ${{ always() }}`控制后续流程。
